name=ArnoTek_HeartBeat
version=1.0.2
author=Anthony Arnovitz, aarnovitz@arnotek.com
maintainer=Anthony Arnovitz, aarnovitz@arnotek.com
sentence=Heartbeat utility for Arduino
paragraph=This utility toggles Arduino pins and/or calls user defined functions at specific time intervals.
category=Timing
url=https://github.com/AJArnovitz/ArnoTek_HeartBeat
architecures=avr